services:
  interactions-server:
    image: ghcr.io/x-ray-explorer-vr/interactions-server
    restart: unless-stopped
    ports:
      - 8080:8080
  # Database
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=555
  # API server
  spectator-api:
    image: ghcr.io/x-ray-explorer-vr/spectator-api
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PASSWORD=555
  spectator-frontend:
    image: ghcr.io/x-ray-explorer-vr/spectator-frontend
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - spectator-api
      - interactions-server
    environment:
      - API_BASE_URL="http://${spectator-api}:5000"
      - WEBSOCKET_URL="http://${interactions-server}:8080"
